### ISSUE TITLE
Stand-alone sampling

### ISSUE THREAD

**Issue by GordStephen** [JuliaRobotics/KernelDensityEstimate.jl#8]
What is the recommended method for using the Gibbs sampler to draw samples from a fit density estimate (independent of any plotting, products, etc)? I would assume this functionality exists in somewhere in `MSGibbs01.jl`, I just haven't been able to isolate it.

**Comment by dehann** [comment]
Hi, yes the Gibbs sampling is used to approximate the product between ```n``` densities of dimension ```d```, such as this one and others shown in the README:
```julia
using Distributions, KernelDensityEstimate
p = kde!(rand(Beta(1.0,0.45),300));
q = kde!(rand(Rayleigh(0.5),100)-0.5);
dummy = kde!(rand(1,100),[1.0]);
pGM, = prodAppxMSGibbsS(dummy, [p;q], Union{}, Union{}, 5)
pq = kde!(pGM)
plotKDE([p;q;pq],c=["red";"green";"black"])
```
![alt tag](https://raw.githubusercontent.com/dehann/KernelDensityEstimate.jl/master/test/RayleighBetaProduct.png)

The library is heavily optimized for taking products of KDEs rather than generic Gibbs sampling of densities. If you are looking for more general MCMC methods which support Gibbs then maybe Mamba.jl, Lora.jl, Stan.jl is more what you are looking for? We are using this package to specifically for KDE products.

**Comment by dehann** [comment]
Yes this is an d-dimensional KDE package. Aside: I am also looking for 'heatmap'  to KDE 'converter' function. I don't think there is such a function available in the Julia ecosystem yet -- please let me know someone knows of one.
